# Initial Data Cleaning - Public Transport Stops Dataset
### Notebook Done By: Kai/Su

This notebook contains some of the processes for the Initial Data Cleaning phase, specifically for cleaning the public transport stops dataset. This notebook covers the process of cleaning the public transport stops dataset.

In [ ]:
# Importing libraries

import pandas as pd
import os

In [ ]:
# Listing the directory

print(os.listdir())

['kk.ipynb', 'ofsted.ipynb', 'stop.ipynb']

In [ ]:
# Loading the public transport stops dataset

df = pd.read_csv("../../data/raw/Stops.csv")

print("Dataset Shape:", df.shape)
df.head()

C:\Users\Nitro\AppData\Local\Temp\ipykernel_50840\918502184.py:1: DtypeWarning: Columns (1,2,6,8,21,22,23,24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../../data/raw/Stops.csv")

Dataset Shape: (434124, 43)

,ATCOCode,NaptanCode,PlateCode,CleardownCode,CommonName,CommonNameLang,ShortCommonName,ShortCommonNameLang,Landmark,LandmarkLang,...,TimingStatus,DefaultWaitTime,Notes,NotesLang,AdministrativeAreaCode,CreationDateTime,ModificationDateTime,RevisionNumber,Modification,Status
0,0100BRP90317,bstjada,NaN,NaN,Temple Meads Stn,NaN,Temple Meads Stn,NaN,NaN,NaN,...,OTH,NaN,NaN,NaN,9,2009-08-25T00:00:00,2019-08-06T11:10:46,49.0,new,active
1,0100BRP90318,bstgwtd,NaN,NaN,Temple Meads Stn,NaN,Temple Meads Stn,NaN,NaN,NaN,...,OTH,NaN,NaN,NaN,9,2009-08-25T00:00:00,2024-01-12T11:30:59,86.0,new,active
2,0100BRP90310,bstgwpa,NaN,NaN,Temple Meads Stn,NaN,Temple Meads Stn,NaN,NaN,NaN,...,OTH,NaN,NaN,NaN,9,2009-08-25T00:00:00,2023-04-21T18:02:19,99.0,new,active
3,0100BRP90311,bstgwpm,NaN,NaN,Temple Meads Stn,NaN,Temple Meads Stn,NaN,NaN,NaN,...,OTH,NaN,NaN,NaN,9,2009-08-25T00:00:00,2019-09-13T10:41:38,73.0,new,active
4,010000056,bstpjgw,NaN,NaN,Temple Meads Stn,NaN,Temple Meads Stn,NaN,NaN,NaN,...,OTH,NaN,NaN,NaN,9,2019-08-06T00:00:00,2025-04-17T09:38:46,120.0,new,active

In [ ]:
# Reviewing the public transport stops dataset's info

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434124 entries, 0 to 434123
Data columns (total 43 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   ATCOCode                 434124 non-null  object
 1   NaptanCode               408146 non-null  object
 2   PlateCode                62815 non-null   object
 3   CleardownCode            0 non-null       float64
 4   CommonName               434124 non-null  object
 5   CommonNameLang           0 non-null       float64
 6   ShortCommonName          93573 non-null   object
 7   ShortCommonNameLang      0 non-null       float64
 8   Landmark                 247648 non-null  object
 9   LandmarkLang             0 non-null       float64
 10  Street                   409835 non-null  object
 11  StreetLang               0 non-null       float64
 12  Crossing                 0 non-null       float64
 13  CrossingLang             0 non-null       float64
 14  Indicator                410249 non-null  object
 15  IndicatorLang            0 non-null       float64
 16  Bearing                  410857 non-null  object
 17  NptgLocalityCode         434124 non-null  object
 18  LocalityName             434107 non-null  object
 19  ParentLocalityName       189640 non-null  object
 20  GrandParentLocalityName  0 non-null       float64
 21  Town                     157166 non-null  object
 22  TownLang                 15263 non-null   object
 23  Suburb                   70678 non-null   object
 24  SuburbLang               11675 non-null   object
 25  LocalityCentre           427669 non-null  object
 26  GridType                 418544 non-null  object
 27  Easting                  434124 non-null  int64
 28  Northing                 434124 non-null  int64
 29  Longitude                381691 non-null  float64
 30  Latitude                 381691 non-null  float64
 31  StopType                 434124 non-null  object
 32  BusStopType              415800 non-null  object
 33  TimingStatus             418994 non-null  object
 34  DefaultWaitTime          0 non-null       float64
 35  Notes                    0 non-null       float64
 36  NotesLang                0 non-null       float64
 37  AdministrativeAreaCode   434124 non-null  int64
 38  CreationDateTime         434124 non-null  object
 39  ModificationDateTime     433703 non-null  object
 40  RevisionNumber           423101 non-null  float64
 41  Modification             398763 non-null  object
 42  Status                   434124 non-null  object
dtypes: float64(15), int64(3), object(25)
memory usage: 142.4+ MB

In [ ]:
# Reviewing columns in the public transport stops dataset

df.columns

Index(['ATCOCode', 'NaptanCode', 'PlateCode', 'CleardownCode', 'CommonName',
       'CommonNameLang', 'ShortCommonName', 'ShortCommonNameLang', 'Landmark',
       'LandmarkLang', 'Street', 'StreetLang', 'Crossing', 'CrossingLang',
       'Indicator', 'IndicatorLang', 'Bearing', 'NptgLocalityCode',
       'LocalityName', 'ParentLocalityName', 'GrandParentLocalityName', 'Town',
       'TownLang', 'Suburb', 'SuburbLang', 'LocalityCentre', 'GridType',
       'Easting', 'Northing', 'Longitude', 'Latitude', 'StopType',
       'BusStopType', 'TimingStatus', 'DefaultWaitTime', 'Notes', 'NotesLang',
       'AdministrativeAreaCode', 'CreationDateTime', 'ModificationDateTime',
       'RevisionNumber', 'Modification', 'Status'],
      dtype='object')

In [ ]:
# Reviewing descriptive statistics for the public transport stops dataset

df.describe()

,CleardownCode,CommonNameLang,ShortCommonNameLang,LandmarkLang,StreetLang,Crossing,CrossingLang,IndicatorLang,GrandParentLocalityName,Easting,Northing,Longitude,Latitude,DefaultWaitTime,Notes,NotesLang,AdministrativeAreaCode,RevisionNumber
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,434124.000000,4.341240e+05,381691.000000,381691.000000,0.0,0.0,0.0,434124.000000,423101.000000
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,414893.020151,3.385917e+05,-1.752633,52.819288,NaN,NaN,NaN,85.441091,10.974947
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101946.814858,1.909583e+05,1.457597,1.707314,NaN,NaN,NaN,31.155184,25.394757
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000e+00,-7.557259,49.766806,NaN,NaN,NaN,1.000000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,347884.750000,1.871208e+05,-2.683207,51.505720,NaN,NaN,NaN,75.000000,1.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,414797.000000,3.071835e+05,-1.666501,52.625995,NaN,NaN,NaN,87.000000,3.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,488653.000000,4.218470e+05,-0.696432,53.604365,NaN,NaN,NaN,105.000000,6.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,759596.000000,1.216444e+06,1.759010,60.825891,NaN,NaN,NaN,153.000000,1123.000000

In [ ]:
# Standardising column names in the public transport stops dataset into format easier to type

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

df.columns

Index(['atcocode', 'naptancode', 'platecode', 'cleardowncode', 'commonname',
       'commonnamelang', 'shortcommonname', 'shortcommonnamelang', 'landmark',
       'landmarklang', 'street', 'streetlang', 'crossing', 'crossinglang',
       'indicator', 'indicatorlang', 'bearing', 'nptglocalitycode',
       'localityname', 'parentlocalityname', 'grandparentlocalityname', 'town',
       'townlang', 'suburb', 'suburblang', 'localitycentre', 'gridtype',
       'easting', 'northing', 'longitude', 'latitude', 'stoptype',
       'busstoptype', 'timingstatus', 'defaultwaittime', 'notes', 'noteslang',
       'administrativeareacode', 'creationdatetime', 'modificationdatetime',
       'revisionnumber', 'modification', 'status'],
      dtype='object')

In [ ]:
# Dropping empty rows

df = df.dropna(how='all')

print("After removing empty rows:", df.shape)

After removing empty rows: (434124, 43)

In [ ]:
# Dropping duplicate rows

df = df.drop_duplicates()

print("After removing duplicates:", df.shape)

After removing duplicates: (434124, 43)

In [ ]:
# Filling missing values with "Unknown"

for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].fillna("Unknown")

Earlier, there are date columns in the public transport stops dataset that are not the ```datetime``` data type. This will be fixed in the next cell.

In [ ]:
# Converting date columns into datetime

if 'creationdatetime' in df.columns:
    df['creationdatetime'] = pd.to_datetime(df['creationdatetime'], errors='coerce')

if 'modificationdatetime' in df.columns:
    df['modificationdatetime'] = pd.to_datetime(df['modificationdatetime'], errors='coerce')

In [ ]:
# Ensuring that columns with numerical values are of numeric data types

for col in ['latitude', 'longitude', 'easting', 'northing']:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

In [ ]:
# Reviewing the shape of the public transport stops dataset

df.shape

(434124, 43)

In [ ]:
# Exporting the public transport stops dataset into a CSV file

df.to_csv("../../data/partially_processed/stops.csv", index=False)

print("Cleaned file saved successfully")

Cleaned file saved successfully

The Initial Data Cleaning phase has concluded, and the Final Data Cleaning phase can begin to ensure that all datasets are truly clean.

The next notebook is ```notebooks/final_data_cleaning.ipynb```.