In [1]:
import pandas as pd
import numpy as np

In [5]:
df_property = pd.read_csv('../data/raw/properties.csv')

df_property

,fullAddress,postcode,country,outcode,latitude,longitude,bathrooms,bedrooms,floorAreaSqM,livingRooms,...,saleEstimate_upperPrice,saleEstimate_confidenceLevel,saleEstimate_ingestedAt,saleEstimate_valueChange.numericChange,saleEstimate_valueChange.percentageChange,saleEstimate_valueChange.saleDate,history_date,history_price,history_percentageChange,history_numericChange
0,"Flat 19, 32 Grosvenor Street, London, W1K 4QS",W1K 4QS,England,W1K,51.511674,-0.148262,1.0,1.0,423.0,1.0,...,836000.0,HIGH,2025-01-10 11:04:57.114000+00:00,679000.0,577.446809,1999-06-15,1995-02-28,81500,16.428571,11500.0
1,"19 Oakbank Grove, London, SE24 0AL",SE24 0AL,England,SE24,51.461643,-0.098031,1.0,2.0,69.0,1.0,...,630000.0,HIGH,2024-10-07 13:26:59.894000+00:00,30000.0,5.263158,2019-10-04,1995-03-07,65000,44.605117,20050.0
2,"55 Bollo Lane, London, W4 5LU",W4 5LU,England,W4,51.496918,-0.270873,1.0,2.0,72.0,1.0,...,493000.0,HIGH,2024-10-07 13:26:59.894000+00:00,50000.0,11.904762,2024-04-24,1995-03-23,16950,-50.869565,-17550.0
3,"38A Worlingham Road, London, SE22 9HD",SE22 9HD,England,SE22,51.460259,-0.072738,1.0,2.0,76.0,1.0,...,717000.0,HIGH,2024-10-07 13:26:59.894000+00:00,-42000.0,-5.793103,2022-08-12,1995-03-30,46000,142.105263,27000.0
4,"1 Derwentwater Road, London, W3 6DE",W3 6DE,England,W3,51.509771,-0.270473,1.0,4.0,171.0,1.0,...,1178000.0,HIGH,2024-10-07 13:26:59.894000+00:00,37000.0,3.410138,2023-10-20,1995-04-03,130000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157266,"9 Harvard Road, London, SE13 6SE",SE13 6SE,England,SE13,51.452919,-0.010221,2.0,3.0,123.0,2.0,...,711000.0,HIGH,2025-01-10 11:04:57.114000+00:00,27000.0,4.153846,2024-09-27,2024-09-27,650000,17.117117,95000.0
157267,"Lower Ground Floor Flat 5, Northwood Hall, Hor...",N6 5PE,England,N6,51.571692,-0.137007,1.0,2.0,60.0,1.0,...,473000.0,HIGH,2025-01-10 11:04:57.114000+00:00,10000.0,2.272727,2024-09-27,2024-09-27,440000,2.325581,10000.0
157268,"17 Merritt Road, London, SE4 1DU",SE4 1DU,England,SE4,51.456054,-0.035073,2.0,3.0,100.0,1.0,...,853000.0,HIGH,2025-01-10 11:04:57.114000+00:00,38000.0,4.909561,2024-09-27,2024-09-27,774000,128.655835,435500.0
157269,"15 Chester Row, London, SW1W 9JF",SW1W 9JF,England,SW1W,51.493587,-0.152122,3.0,4.0,218.0,2.0,...,5975000.0,MEDIUM,2025-01-10 11:04:57.114000+00:00,-818000.0,-13.088000,2024-09-27,2024-09-27,6250000,73.611111,2650000.0
157270,"56 Whiteley Road, London, SE19 1JT",SE19 1JT,England,SE19,51.424412,-0.090256,1.0,5.0,154.0,2.0,...,1031000.0,HIGH,2025-01-10 11:04:57.114000+00:00,55000.0,5.876011,2024-09-27,2024-09-27,927500,692.735043,810500.0

In [4]:
df_schools = pd.read_csv('../data/raw/schools.csv')

df_schools

,1000000,the_aldgate_school,20250402t000000,os,statefunded_schools,20241231t000000,20240711t000000,london,city_of_london,cities_of_london_and_westminster,ec3a_5de,local_authority_maintained,voluntary_aided_school,primary,deprived,10,yes,20,90
0,100005.0,Thomas Coram Centre,2025-04-02T00:00:00,OS,State-funded schools,2024-12-31T00:00:00,2014-07-02T00:00:00,London,Camden,Holborn and St Pancras,WC1N 2NY,Local authority maintained,LA Nursery School,Nursery,Average,1.0,9.0,9.0,9.0
1,100006.0,Heath School,2025-04-02T00:00:00,OS,State-funded schools,2024-12-31T00:00:00,2024-07-04T00:00:00,London,Camden,Hampstead and Highgate,NW3 2NY,Local authority maintained,Pupil Referral Unit,PRU,Average,2.0,1.0,9.0,9.0
2,100007.0,Camden Primary Pupil Referral Unit,2025-04-02T00:00:00,OS,State-funded schools,2024-12-31T00:00:00,2015-05-05T00:00:00,London,Camden,Holborn and St Pancras,NW1 3EX,Local authority maintained,Pupil Referral Unit,PRU,Deprived,2.0,9.0,9.0,9.0
3,100008.0,Argyle Primary School,2025-04-02T00:00:00,OS,State-funded schools,2024-12-31T00:00:00,2022-11-17T00:00:00,London,Camden,Holborn and St Pancras,WC1H 9EG,Local authority maintained,Community School,Primary,Deprived,2.0,1.0,2.0,9.0
4,100009.0,West Hampstead Primary School,2025-04-02T00:00:00,OS,State-funded schools,2024-12-31T00:00:00,2012-09-10T00:00:00,London,Camden,Hampstead and Highgate,NW6 1QL,Local authority maintained,Community School,Primary,Deprived,2.0,9.0,8.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131923,148026.0,"St Antony's Roman Catholic School, a Voluntary...",2024-12-03T00:00:00,OS,State-funded schools,2020-08-31T00:00:00,2019-11-28T00:00:00,North West,Trafford,Stretford and Urmston,M41 9PD,Academy sponsor led,Academy Sponsor Led,Secondary,Unknown,4.0,1.0,9.0,9.0
131924,148036.0,Gloucester Academy,2024-12-03T00:00:00,OS,State-funded schools,2020-08-31T00:00:00,2018-05-29T00:00:00,South West,Gloucestershire,Gloucester,GL4 6RN,Academy sponsor led,Academy Sponsor Led,Secondary,Unknown,4.0,0.0,9.0,3.0
131925,148039.0,Northbrook Primary Academy,2024-12-03T00:00:00,OS,State-funded schools,2020-08-31T00:00:00,2019-11-18T00:00:00,North West,Lancashire,South Ribble,PR25 2GB,Academy sponsor led,Academy Sponsor Led,Primary,Unknown,4.0,1.0,3.0,9.0
131926,148050.0,"St Monica's RC High School, a Voluntary Academy",2024-12-03T00:00:00,OS,State-funded schools,2020-08-31T00:00:00,2019-12-19T00:00:00,North West,Bury,Bury South,M25 1JH,Academy sponsor led,Academy Sponsor Led,Secondary,Unknown,3.0,1.0,9.0,9.0
131927,131962.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,3.0,9.0

In [6]:
df_crime = pd.read_csv('../data/raw/crime.csv')

df_crime

,crime_id,month,reported_by,falls_within,longitude,latitude,location,lsoa_code,lsoa_name,crime_type,last_outcome_category,context
0,069e2f376970cacf27fdebd3605c8679c36b4b534d9d8e...,2024-08-01,City of London Police,City of London Police,-0.107682,51.517786,On or near B521,E01000917,Camden 027C,Public order,Court result unavailable,NaN
1,8c688259358e5e17ed437731a6b3e35758d77a76891dc1...,2024-08-01,City of London Police,City of London Police,-0.111596,51.518281,On or near Chancery Lane,E01000914,Camden 028B,Shoplifting,Investigation complete; no suspect identified,NaN
2,5211a4a565d73dd4cbf526d112fde0375d8cb3c20a3d60...,2024-08-01,City of London Police,City of London Police,-0.112096,51.515942,On or near Nightclub,E01000914,Camden 028B,Theft from the person,Investigation complete; no suspect identified,NaN
3,b60eab510955bd9359d900f502807f4cb9317c6c9326eb...,2024-08-01,City of London Police,City of London Police,-0.097245,51.515387,On or near St Martin'S Le Grand,E01000001,City of London 001A,Criminal damage and arson,Status update unavailable,NaN
4,750ecac3560cde0297f40009e4f07459f9d846289e2b0b...,2024-08-01,City of London Police,City of London Police,-0.098519,51.517332,On or near Little Britain,E01000001,City of London 001A,Drugs,Offender given a drugs possession warning,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1975532,6fbe6e76cd99665e5ea2be86f713dbe0c116f5c26e779c...,2023-11-01,Metropolitan Police Service,Metropolitan Police Service,-0.605843,51.481873,On or near St Alban'S Street,E01016544,Windsor and Maidenhead 010A,Possession of weapons,Status update unavailable,NaN
1975533,c70a42e476f696cfa8ea100ad0dd52e260b10931ee1651...,2023-11-01,Metropolitan Police Service,Metropolitan Police Service,-0.605843,51.481873,On or near St Alban'S Street,E01016544,Windsor and Maidenhead 010A,Possession of weapons,Status update unavailable,NaN
1975534,4f8d9bfc430c96ae2074e0a4958cc13a4d2caa371bd08f...,2023-11-01,Metropolitan Police Service,Metropolitan Police Service,-0.619305,51.479595,On or near Fawcett Road,E01016545,Windsor and Maidenhead 012A,Violence and sexual offences,Investigation complete; no suspect identified,NaN
1975535,ea196c8fdb243f2409dfa8dadabf408cd40beb240ae2b0...,2023-11-01,Metropolitan Police Service,Metropolitan Police Service,-0.569901,51.323626,On or near Wilson Way,E01030968,Woking 003F,Violence and sexual offences,Status update unavailable,NaN
1975536,2729e70f748ec092b95bfc6611176dce7352b99ef1bbae...,2023-11-01,Metropolitan Police Service,Metropolitan Police Service,-0.845350,51.411658,On or near Frederick Place,E01016626,Wokingham 013A,Violence and sexual offences,Investigation complete; no suspect identified,NaN

In [9]:
df_stops = pd.read_csv('../data/raw/stops.csv')

df_stops

C:\Users\Nitro\AppData\Local\Temp\ipykernel_37596\2858847160.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df_stops = pd.read_csv('../data/raw/stops.csv')

,atcocode,naptancode,platecode,cleardowncode,commonname,commonnamelang,shortcommonname,shortcommonnamelang,landmark,landmarklang,...,timingstatus,defaultwaittime,notes,noteslang,administrativeareacode,creationdatetime,modificationdatetime,revisionnumber,modification,status
0,0100BRP90317,bstjada,Unknown,NaN,Temple Meads Stn,NaN,Temple Meads Stn,NaN,Unknown,NaN,...,OTH,NaN,NaN,NaN,9,2009-08-25,2019-08-06 11:10:46,49.0,new,active
1,0100BRP90318,bstgwtd,Unknown,NaN,Temple Meads Stn,NaN,Temple Meads Stn,NaN,Unknown,NaN,...,OTH,NaN,NaN,NaN,9,2009-08-25,2024-01-12 11:30:59,86.0,new,active
2,0100BRP90310,bstgwpa,Unknown,NaN,Temple Meads Stn,NaN,Temple Meads Stn,NaN,Unknown,NaN,...,OTH,NaN,NaN,NaN,9,2009-08-25,2023-04-21 18:02:19,99.0,new,active
3,0100BRP90311,bstgwpm,Unknown,NaN,Temple Meads Stn,NaN,Temple Meads Stn,NaN,Unknown,NaN,...,OTH,NaN,NaN,NaN,9,2009-08-25,2019-09-13 10:41:38,73.0,new,active
4,010000056,bstpjgw,Unknown,NaN,Temple Meads Stn,NaN,Temple Meads Stn,NaN,Unknown,NaN,...,OTH,NaN,NaN,NaN,9,2019-08-06,2025-04-17 09:38:46,120.0,new,active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434119,9400ZZBPTAL,Unknown,Unknown,NaN,Talbot Road (Blackpool Tramway),NaN,Unknown,NaN,Promenade,NaN,...,Unknown,NaN,NaN,NaN,147,2024-05-29 12:00:00,2024-05-29 12:00:00,0.0,new,active
434120,9400ZZBPTAL1,blpamtam,Unknown,NaN,Talbot Road (Blackpool Tramway),NaN,Unknown,NaN,Promenade,NaN,...,Unknown,NaN,NaN,NaN,147,2024-05-29 12:00:00,2024-05-29 11:00:00,0.0,new,active
434121,9400ZZBPNRS,Unknown,Unknown,NaN,North Station (Blackpool Tramway),NaN,Unknown,NaN,Unknown,NaN,...,Unknown,NaN,NaN,NaN,147,2024-05-29 12:00:00,2024-05-29 12:00:00,0.0,new,active
434122,9400ZZBPNRS1,blpamtap,Unknown,NaN,North Station (Blackpool Tramway),NaN,Unknown,NaN,Unknown,NaN,...,Unknown,NaN,NaN,NaN,147,2024-05-29 12:00:00,2024-05-29 11:00:00,0.0,new,active
434123,9400ZZBPNRS2,blpamtat,Unknown,NaN,North Station (Blackpool Tramway),NaN,Unknown,NaN,Unknown,NaN,...,Unknown,NaN,NaN,NaN,147,2024-05-29 12:00:00,2024-05-29 12:00:00,0.0,new,active